#!/bin/sh -e

SOTA_DIR="${SOTA_DIR-/var/sota}"

if [ "$1" = "get" ] ; then
    if [ ! -f ${SOTA_DIR}/sota.toml ] ; then
        echo "ERROR: Device does not appear to be registered under $SOTA_DIR"
        exit 1
    fi
    server=$(grep -m1 '^[[:space:]]*server' ${SOTA_DIR}/sota.toml | cut -d\" -f2)
    if [ -z $server ] ; then
        server="https://ota-lite.foundries.io:8443"
    fi
    exec /usr/local/bin/fioup http get ${server}/hub-creds/
fi
