name: CI
on:
  pull_request:

jobs:

  lint:
    name: Run golint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

  e2e-test-granular:
    name: End-to-end tests using granular commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/fioup/fioup
      - run: ./dev-shell.sh make build test-e2e-granular
        env:
          FACTORY: ${{ secrets.E2E_TEST_FACTORY }}
          BASE_TARGET_VERSION: ${{ secrets.E2E_TEST_BASE_TARGET_VERSION }}
          USER_TOKEN: ${{ secrets.E2E_TEST_USER_TOKEN }}
          TAG: ${{secrets.E2E_TEST_TAG}}

  e2e-test-single-command:
    name: End-to-end tests using single update command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/fioup/fioup
      - run: ./dev-shell.sh make build test-e2e-single-command
        env:
          FACTORY: ${{ secrets.E2E_TEST_FACTORY }}
          BASE_TARGET_VERSION: ${{ secrets.E2E_TEST_BASE_TARGET_VERSION }}
          USER_TOKEN: ${{ secrets.E2E_TEST_USER_TOKEN }}
          TAG: ${{secrets.E2E_TEST_TAG}}


  package:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build for Debian
        run: |
          make deb DEBS_DIR=/tmp/debs
          docker run --rm -i -v /tmp:/host-tmp debian:trixie <<EOF
          set -ex

          apt update && apt install -y lshw 
          dpkg -i /host-tmp/debs/fioup_*.deb

          test -x /usr/bin/fioup
          test -x /usr/bin/docker-credential-fioup
          test -f /usr/share/bash-completion/completions/fioup
          test -f /lib/systemd/system/fioup.service
          EOF
